const KEYS={products:'plb_products',documents:'plb_documents',inquiries:'plb_inquiries'};
const load=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let products=load(KEYS.products),documents=load(KEYS.documents),inquiries=load(KEYS.inquiries);
function render(){
 document.getElementById('productCount').textContent=products.length;
 document.getElementById('documentCount').textContent=documents.length;
 document.getElementById('newInquiryCount').textContent=inquiries.filter(x=>x.status==='접수').length;
 document.getElementById('productRows').innerHTML=products.length?products.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${esc(x.maker)}</td><td><span class="badge">${esc(x.category)}</span></td><td>${esc(x.package)}</td><td>${esc(x.description)}</td><td><button class="btn danger" data-del-product="${x.id}">삭제</button></td></tr>`).join(''):'<tr><td colspan="6" class="empty">등록된 제품이 없습니다.</td></tr>';
 document.getElementById('documentRows').innerHTML=documents.length?documents.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td><span class="badge">${esc(x.type)}</span></td><td>${esc(x.maker)}</td><td>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener" style="color:#fff">열기</a>`:'-'}</td><td><button class="btn danger" data-del-document="${x.id}">삭제</button></td></tr>`).join(''):'<tr><td colspan="5" class="empty">등록된 자료가 없습니다.</td></tr>';
 document.getElementById('inquiryRows').innerHTML=inquiries.length?inquiries.map(x=>`<tr><td>${esc(x.company)}</td><td>${esc(x.name)}</td><td><a href="tel:${esc(x.phone)}" style="color:#fff">${esc(x.phone)}</a></td><td>${esc(x.product)}</td><td>${esc(x.message)}</td><td><select data-status="${x.id}"><option ${x.status==='접수'?'selected':''}>접수</option><option ${x.status==='처리중'?'selected':''}>처리중</option><option ${x.status==='완료'?'selected':''}>완료</option></select></td><td><button class="btn danger" data-del-inquiry="${x.id}">삭제</button></td></tr>`).join(''):'<tr><td colspan="7" class="empty">접수된 문의가 없습니다.</td></tr>';
}
document.getElementById('productForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);products.unshift({id:crypto.randomUUID(),name:f.get('name'),maker:f.get('maker'),category:f.get('category'),package:f.get('package'),description:f.get('description'),createdAt:new Date().toISOString()});save(KEYS.products,products);e.currentTarget.reset();render();});
document.getElementById('documentForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);documents.unshift({id:crypto.randomUUID(),title:f.get('title'),type:f.get('type'),maker:f.get('maker'),url:f.get('url'),createdAt:new Date().toISOString()});save(KEYS.documents,documents);e.currentTarget.reset();render();});
document.getElementById('sampleInquiry').addEventListener('click',()=>{inquiries.unshift({id:crypto.randomUUID(),company:'테스트 제조업체',name:'홍길동',phone:'010-0000-0000',product:'분체도료',message:'제품 견적과 납기 문의입니다.',status:'접수',createdAt:new Date().toISOString()});save(KEYS.inquiries,inquiries);render();});
document.addEventListener('click',e=>{const t=e.target;if(t.dataset.delProduct){products=products.filter(x=>x.id!==t.dataset.delProduct);save(KEYS.products,products);render()}if(t.dataset.delDocument){documents=documents.filter(x=>x.id!==t.dataset.delDocument);save(KEYS.documents,documents);render()}if(t.dataset.delInquiry){inquiries=inquiries.filter(x=>x.id!==t.dataset.delInquiry);save(KEYS.inquiries,inquiries);render()}});
document.addEventListener('change',e=>{if(e.target.dataset.status){const item=inquiries.find(x=>x.id===e.target.dataset.status);if(item){item.status=e.target.value;save(KEYS.inquiries,inquiries);render()}}});
document.getElementById('exportData').addEventListener('click',()=>{const data={exportedAt:new Date().toISOString(),products,documents,inquiries};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`plb-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});
document.getElementById('clearData').addEventListener('click',()=>{if(!confirm('등록된 제품, 자료, 문의를 모두 삭제할까요?'))return;products=[];documents=[];inquiries=[];Object.values(KEYS).forEach(k=>localStorage.removeItem(k));render()});
render();